
### AI Extract Method 
POST {{Api_HostAddress}}/AI/extract
Accept: */*
Content-Type: application/json
x-google-idtoken:{{Google_IdToken}}

{
  "Language": "en-US",
  "Prompt": "Create an expense for today with the amount of €10. It was spent on a cafeteria named Ho Ho."
}

### Match Expenses
GET {{Api_HostAddress}}/Expense/match/
Accept: */*
Content-Type: application/json
x-google-idtoken:{{Google_IdToken}}


### List Account Transactions
@DateFrom = 2024-04-01
@DateTo = 2024-04-12
GET {{Api_HostAddress}}/Account/transactions/?dateFrom={{DateFrom}}&dateTo={{DateTo}}
Accept: */*
Content-Type: application/json
x-google-idtoken:{{Google_IdToken}}


### Create Expense
POST {{Api_HostAddress}}/Expense/
Accept: */*
Content-Type: application/json
x-google-idtoken:{{Google_IdToken}}

{
  "date": "2024-03-19T12:15:42.953Z",
  "amount": 10,
  "description": "Dote",
  "category": "Eating out"
}

### List Latest Expenses
GET {{Api_HostAddress}}/Expense/latest/5
Accept: */*
Content-Type: application/json
x-google-idtoken:{{Google_IdToken}}


### List Categories
GET {{Api_HostAddress}}/Category/
Accept: */*
Content-Type: application/json
x-google-idtoken:{{Google_IdToken}}


### Health Check
GET {{Api_HostAddress}}/healthz/
Accept: */*
Content-Type: application/json
x-google-idtoken:{{Google_IdToken}}

###